language: python

sudo: false

env:
    matrix:
        - PYTHON_VERSION=3.5

install:
    # Install Miniconda so we can use it to manage dependencies:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda3
    - export PATH="$HOME/miniconda3/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    # Create a conda environment with the required python version and other
    # dependencies, currently versioneer is not available on the default
    # Anaconda channel but it can be installed via pip:
    - conda create -n scmtiles-test --file conda-requirements.txt
    - source activate scmtiles-test
    - pip install versioneer
    # Install scmtiles:
    - python setup.py install

script:
    - py.test

notifications:
    email: false
